title:              'Nicholas Dille'
tagline:            'Automation, DevOps and Containerization'
description:        'Automation, DevOps and Containerization'
url:                https://dille.name
keywords:           'automation, virtualization, powershell, docker, container, devops'
#baseurl:           /blog/

author:
  name:             'Nicholas Dille'
  url:              https://twitter.com/nicholasdille

twitter:
  username: nicholasdille
  card: summary

social:
  name: Nicholas Dille
  links:
    - https://twitter.com/nicholasdille
    - https://www.linkedin.com/in/nicholasdille/
    - https://www.xing.com/profile/Nicholas_Dille

lang: en_US

webmaster_verifications:
  google: MFi9wm_TjR4XDF8yNCEc1V1pRO3vkro_COmJtsySst4
  bing: 0FC8353843842EB96168534BE11FA269

collections:
  snippets:
    output: true

plugins:
 - jekyll-paginate
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-mentions

include:
 - .htaccess
 - .well-known

exclude:
 - .git
 - Dockerfile
 - psakefile.ps1
 - CNAME
 - README.md
 - Set-StaticAzureWebsite.clixml
 - Set-StaticAzureWebsite.ps1

markdown:           kramdown
highlighter:        rouge
permalink:          pretty

kramdown:
  auto_ids: true

paginate:           10
paginate_path:      /blog/page:num/
excerpt_separator:  <!--more-->

jekyll-mentions:
  base_url: https://www.twitter.com

